### PR TITLE
Link click handler

### PR DESCRIPTION
**Pull request by kosbog**
Issue https://github.com/wxik/react-native-rich-editor/issues/187

### CODE REVIEW

**Comment by kosbog** [comment]
@stulip check PR, please.

**Comment by jakehasler** [comment]
@kosbog  I was also just looking for this functionality. I've got my own fork in my project now with a few small things. I'm going to try merging this into mine and seeing how it works 👍

**Comment by kosbog** [comment]
@jakehasler super. Just let me know!

**Comment by jakehasler** [comment]
@kosbog I did find a bug - that when the editor is set to `disabled`, it was executing the function but couldn't find the `Linking` variable in the scope. I haven't had a chance to look into it yet, but just an FYI.

image
image

**Comment by kosbog** [comment]
@jakehasler ah, my stupid mistake...
Fixed.

**Comment by jakehasler** [comment]
@kosbog I tested it out and it turned out that it was redirecting to the link right in the Webview itself, replacing the current editor content. So I adjusted my branch to have the following code:
image
Commit 1: https://github.com/jakehasler/react-native-rich-editor/commit/97a06439ec4f70447ab1a233b6cd4a12ce2bb7a3
Commit 2: https://github.com/jakehasler/react-native-rich-editor/commit/6f0580a4eb8ff16f716ec99a2f108f6f71002a9a


Also, I changed to `onShouldStartLoadWithRequest` to improve android compatibility based on this answer:
https://github.com/react-native-webview/react-native-webview/issues/1625#issuecomment-754566686

**Comment by kosbog** [comment]
@jakehasler super!

**Comment by stulip** [comment]
Thank you, the code is conflict, please make a correction before submitting it

**Comment by kosbog** [comment]
Update a branch.

**Pull request merged**
