### PR TITLE
Update editor.js

### PR DESCRIPTION
**Pull request by cristianoccazinsp**
If not useContainer, allow client height to be 100% so it adjusts automatically.

This should fix issues with the parent view changing height.

### CODE REVIEW

**Comment by cristianoccazinsp** [comment]
@stulip would you consider merging this?

**Comment by stulip** [comment]
I need to test, why is the height instead of 100%

**Comment by stulip** [comment]
I remembered that there is a 100% problem with a certain version of `react-native-webview`

**Comment by stulip** [comment]
Selectively modified

**Comment by cristianoccazinsp** [comment]
How did you resolve it after all? I’ve been using the 100% patch and it seems to be working fine. The web view height adjusts to its parent view and the editor works as expected, even after rotations or parent view height changes .

**Comment by cristianoccazinsp** [comment]
@stulip thanks, worked fine!

**Pull request closed without merging**
